package dev.mobilerevolution.starter
// Generated by CommonImages
data class Image(val name: String)
object Images {
	val CIRCUIT_HUNGARORING: Image = Image("circuit_hungaroring")
	val CIRCUIT_MEXICO: Image = Image("circuit_mexico")
	val IC_BOTTOMMENU_HOME: Image = Image("ic_bottommenu_home")
	val CIRCUIT_REDBULLRING: Image = Image("circuit_redbullring")
	val CIRCIUT_AMERICAS: Image = Image("circiut_americas")
	val CIRCUIT_ABUDHABI: Image = Image("circuit_abudhabi")
	val CIRCUIT_SUZUKA: Image = Image("circuit_suzuka")
	val CIRCUIT_BAHRAIN: Image = Image("circuit_bahrain")
	val CIRCUIT_CATALUNYA: Image = Image("circuit_catalunya")
	val IC_SETTINGS: Image = Image("ic_settings")
	val CIRCUIT_SILVERSTONE: Image = Image("circuit_silverstone")
	val CIRCUIT_ALBERTPARK: Image = Image("circuit_albertpark")
	val CIRCUIT_PAULRICARD: Image = Image("circuit_paulricard")
	val CIRCUIT_MONACO: Image = Image("circuit_monaco")
	val CIRCUIT_INTERLAGOS: Image = Image("circuit_interlagos")
	val CIRCUIT_BAKU: Image = Image("circuit_baku")
}

