package com.example.kmmtest
// Generated by CommonImages
data class Image(val name: String)
object Images {
	val IC_BOTTOMMENU_HOME: Image = Image("ic_bottommenu_home")
	val PNG_ICON: Image = Image("png_icon")
	val IC_SETTINGS: Image = Image("ic_settings")
}

