// Generated by KMM Resources
package com.example.kmmtest

class L {
  companion object {
    val bottomTab: BottomTab = BottomTab()
  }
  data class BottomTab(
    val season: Season = Season(),
    val standings: Standings = Standings()) {
    class Season {
      operator fun get(key: String): String? = when(key) {
        "tabLabel" -> tabLabel()
        else -> null
      }
    }
    class Standings {
      operator fun get(key: String): String? = when(key) {
        "tabLabel" -> tabLabel()
        else -> null
      }
    }
  }
}


expect fun L.BottomTab.Season.tabLabel(): String
expect fun L.BottomTab.Standings.tabLabel(): String
